name: Run break_link.py on push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install requests beautifulsoup4

      - name: run find_break_link.py
        run: python find_break_link.py
